# Generated by Django 6.0.5 on 2026-05-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(default='')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_prevista', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField(default=0)),
                ('responsable_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_asignados', to='empleado.empleado')),
            ],
        ),
    ]
