# Generated by Django 6.0.5 on 2026-05-25 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='')),
                ('estado', models.IntegerField(default=0)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin_prevista', models.DateField(blank=True, null=True)),
                ('proyecto_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asociadas', to='proyecto.proyecto')),
                ('responsable_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to='empleado.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dependencia', models.CharField(choices=[('FIN_INI', 'Fin → Inicio'), ('INI_INI', 'Inicio → Inicio'), ('FIN_FIN', 'Fin → Fin')], max_length=50)),
                ('tarea_dependiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps_sucesoras', to='tarea.tarea')),
                ('tarea_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps_antecesoras', to='tarea.tarea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tarea_origen', 'tarea_dependiente', 'tipo_dependencia'), name='no_duplicados')],
            },
        ),
    ]
