# Generated by Django 6.0.5 on 2026-05-28 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('tarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='tarea_dependiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deps_sucesoras', to='tarea.tarea'),
        ),
        migrations.AlterField(
            model_name='dependencia',
            name='tarea_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deps_antecesoras', to='tarea.tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='proyecto_asociado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asociadas', to='proyecto.proyecto'),
        ),
    ]
